development:
  adapter: postgresql
  encoding: unicode
  database: twitter_monitor_development
  pool: 5
  username: aersandersonsoares
  password: aersgeorgia
  
  test:
    adapter: postgresql
    encoding: unicode
    database: twitter_monitor_test
    pool: 5
    username: aersandersonsoares
    password: aersgeorgia

  production:
    adapter: postgresql
    encoding: unicode
    database: twitter_monitor_production
    pool: 5
    username: aersandersonsoares
    password: aersgeorgia
  